name: 💡 Idea Submission
description: Submit a new idea or concept for the Somnigraph project
title: "[IDEA] "
labels: ["idea", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your idea! Please provide as much detail as possible.
  
  - type: textarea
    id: summary
    attributes:
      label: Idea Summary
      description: A brief summary of your idea
      placeholder: What is your idea in a nutshell?
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of your idea
      placeholder: |
        Explain your idea in detail:
        - What problem does it solve?
        - How would it work?
        - What are the key features?
    validations:
      required: true
  
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases or scenarios where this idea would be valuable
      placeholder: |
        Example scenarios:
        1. ...
        2. ...
    validations:
      required: false
  
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this idea bring?
      placeholder: |
        - Improved user experience
        - Better performance
        - etc.
    validations:
      required: false
  
  - type: textarea
    id: considerations
    attributes:
      label: Potential Challenges
      description: Any potential challenges or considerations?
      placeholder: Technical limitations, resource requirements, etc.
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references
      placeholder: Links, images, related ideas, etc.
    validations:
      required: false
